#!/bin/sh

uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='time.apple.com'
EOF
uci commit system

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

rm -f /www/luci-static/resources/view/status/include/70_ddns.js
rm -f /www/luci-static/resources/view/status/include/80_upnp.js

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/share/luci/menu.d/luci-app-samba4.json

sed -i 's#downloads.openwrt.org#mirrors.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i 's#downloads.openwrt.org#mirrors.tencent.com/lede#g' /etc/apk/repositories.d/distfeeds.list
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

sed -i '/check_signature/d' /etc/opkg.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R25.10.10'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWRT '" >> /etc/openwrt_release

sed -i '/OPENWRT_RELEASE/d' /usr/lib/os-release
echo 'OPENWRT_RELEASE="OpenWRT R25.10.10"' >> /usr/lib/os-release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

cat << "AEOF" > /root/system_init.sh
#!/bin/bash
#脚本变量
Net_Server=223.5.5.5
RETRY_INTERVAL=5
MAX_RETRIES=8

package="iperf3 openssh-client"

P2p_Version=3.24.27
P2p_token=108848862817014656

Back_cul='https://free.picui.cn/free/2025/10/04/68e020187328c.jpg'

#探测网络
for ((i=0; i<MAX_RETRIES; i++)); do
    if ping -c 5 "$Net_Server" &>/dev/null; then
        echo -e "Net 服务器 $Net_Server 已响应，开始运行初始化脚本。"
        break
    fi
    echo -e "Net 服务器 $Net_Server 未响应，等待 $RETRY_INTERVAL 秒后重试..."
    sleep "$RETRY_INTERVAL"
done

[ $i -ge $MAX_RETRIES ] && {
    echo -e "Net 服务器 $Net_Server 无法连接，已达到最大重试次数。"
    exit 1
}

#清理无用软件源
#sed -e '/qualcommax/d' /etc/opkg/distfeeds.conf -i

#更新软件源
if ! opkg update; then
    echo -e "$(date): opkg update 失败"
    exit 1
fi
echo -e "$(date): opkg update 成功"

#安装额外软件包
for package in $PACKAGES; do
    echo -e "\n正在安装: $package"
    if opkg install "$package"; then
        echo -e "\n安装成功: $package"
    else
        echo -e "\n安装失败: $package"
    fi
done


#部署组网软件
wget --no-check-certificate -O install.sh "https://console.openp2p.cn/download/v1/${P2p_Version}/install.sh" && sh ./install.sh --token ${P2p_token} --ver ${P2p_Version} --domain console.openp2p.cn

permitport=$(grep -o '"PublicIPPort": [0-9]*' /usr/local/openp2p/config.json | sed 's/.*: //')
checkfirewallport=$(cat /etc/config/firewall | grep "${permitport}" | grep -o -E '[0-9]+')

if [ "$permitport" = "$checkfirewallport" ]; then
    echo -e "${permitport}=${checkfirewallport}, 防火墙放行'PublicIPPort' successes"
else
    uci add firewall rule
    uci set firewall.@rule[-1].src='wan'
    uci set firewall.@rule[-1].name='Allow-op'
    uci set firewall.@rule[-1].dest_port="${permitport}"
    uci set firewall.@rule[-1].target='ACCEPT'
    uci add_list firewall.@rule[-1].proto='tcp'
    uci add_list firewall.@rule[-1].proto='udp'
    uci commit firewall
    service firewall restart
fi

#配置密钥登陆
cat > /etc/dropbear/authorized_keys << BEOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCviV+/un+ygCL+em7loKxIQSjsS6Md+lB4bdfW/WbeETNzpxufdWsUWUqDl/lfrKKDd3PI+e2PaoREBWQWJQTVb7s+hKc5sXCNSe9JC9x1X9QTV1cM0v/mVAdoQyg6Y9dmVD6lpn9ZrH4f4g39zz4XTGwkq73K+tr/uEc4Li8M9Q2m2pC6bt++dUDzrmWGW9jJ3s6Otrt6GNtsHASL+pJ5pJNhtRwJpPwJuK5LDju2sJ7FrxDPs9JdPf4RCdYTuVoZ66h7OZyp+/Sty6oGweLJgeJ+9z/gdRLl/Ix95mssRHBxbbvt/BEfFlr7tCCqPnZiazq3R2FYYQ8nJtqdXp9j root@server
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+yhwcof5b16KY2bfaKwx2IRLvUodJUwWEQI173G7/k6X3cB0/fS0d21D4ol0JTkM+I8WgDrDZkq/YpprcaGbO/JO+zbdKY2Qzjl1IqQFDFono+yiCrwVHabwCxRWH4YJZj0fEz2fDWx/3cRwJjTr8F2wxvihrgv7FT4uYlx8iBlpVBsci5Je0ZRqmQX88KSPtrwjrqbxdgqrmLBYW8nFY5H2ol24b/vTeoStQOG3vY4x+iyk0QfIaCvC6zEHz7D7x/CfY7m5nDEf6Qrn1xqWRtVcXR8ISHQ10i7Afd4wSESzGfwN7+ZRHNuIBUD8qISaN6heUercXsGV6p8N+NN0f root@server
BEOF

cat > /etc/config/dropbear << CEOF
config dropbear 'main'
        option PasswordAuth 'on'
        option RootPasswordAuth 'off'
        option Port '22'
        option Interface 'lan'
CEOF

/etc/init.d/dropbear restart


#配置web背景图片
wget ${Back_cul} -O /www/luci-static/argon/background/argon.png

# 恢复初始配置
cat > /etc/rc.local << HEOF
# Put your custom commands here that should be executed once
# the system init finished. By default this file does nothing.
#!/bin/sh

exit 0
HEOF

# 清理自启动脚本
rm -rf /etc/ddns
rm -rf /usr/share/ddns
rm -rf /usr/lib/ddns
rm -rf /etc/init.d/ddns

rm install.sh
rm -f /root/system_init.sh
exit 0

AEOF

# 配置启动脚本
cat > /etc/rc.local << IEOF
#!/bin/sh

bash /root/system_init.sh
exit 0
IEOF

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
